predictions/urls.py
from django.urls import path

from . import views

app_name = "predictions"
urlpatterns = [
    path("", views.PredictionListView.as_view(), name="list"),
    path("vote/", views.create, name="add_prediction"),
]

tournament_pool/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("tournaments/", include("tournaments.urls")),
    path("admin/", admin.site.urls),
    path("", include("predictions.urls")),
]

tournaments/urls.py
from django.urls import path

from . import views

app_name = "tournaments"
urlpatterns = [
    path("", views.TournamentIndexView.as_view(), name="index"),
    path("<int:pk>/", views.TournamentDetailView.as_view(), name="detail"),
]

predictions/models.py
from django.db import models

from tournaments.models import Team, Tournament


class Prediction(models.Model):
    name = models.CharField(max_length=200)
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    winning_team = models.ForeignKey(Team, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} predicts {self.winning_team} will win {self.tournament}"

tournaments/models.py
from django.db import models


class Tournament(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Team(models.Model):
    name = models.CharField(max_length=200)
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

predictions/views.py
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls import reverse
from django.views import generic

from tournaments.models import Team, Tournament

from .models import Prediction


def create(request):
    # This is very arbitrary, but we're ONLY interested in the last tournament.
    tournament = Tournament.objects.last()

    if not tournament:
        raise Http404("No tournament exists. Create one in the admin.")

    try:
        selected_team = tournament.team_set.get(pk=request.POST["team"])
        name = request.POST["name"]
    except (KeyError, Team.DoesNotExist):
        # Redisplay the form.
        teams = tournament.team_set.all()
        return render(
            request,
            "predictions/prediction_form.html",
            {
                "tournament_name": tournament.name,
                "team_list": teams,
                "error_message": "You didn't pick a team yet.",
            },
        )
    else:
        prediction = Prediction(
            tournament=tournament, winning_team=selected_team, name=name
        )
        prediction.save()

        return HttpResponseRedirect(reverse("predictions:list"))


class PredictionListView(generic.ListView):
    template_name = "predictions/prediction_list.html"
    context_object_name = "prediction_list"

    def get_queryset(self):
        tournament = Tournament.objects.last()
        if not tournament:
            raise Http404()

        return tournament.prediction_set.all()

tournaments/views.py
from django.views import generic

from .models import Tournament


class TournamentIndexView(generic.ListView):
    template_name = "tournaments/index.html"
    context_object_name = "tournament_list"

    def get_queryset(self):
        return Tournament.objects.all()


class TournamentDetailView(generic.DetailView):
    model = Tournament
    template_name = "tournaments/detail.html"

predictions/templates/predictions/prediction_form.html
{% load static %}

<link rel="stylesheet" href="{% static 'predictions/style.css' %}">

<form action="{% url 'predictions:add_prediction' %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>Who will win {{ tournament_name }}?</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <input type="text" name="name" id="name" value="">
    {% for team in team_list %}
        <input type="radio" name="team" id="team{{ forloop.counter }}" value="{{ team.id }}">
        <label for="team{{ forloop.counter }}">{{ team.name }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Submit prediction">
</form>

predictions/templates/predictions/prediction_list.html
{% load static %}

<link rel="stylesheet" href="{% static 'predictions/style.css' %}">

<p>
    <a href="{% url 'predictions:add_prediction' %}">Add your prediction</a>
</p>
<ul>
{% for prediction in prediction_list %}
    <li>{{ prediction }}</li>
{% endfor %}
</ul>

tournaments/templates/tournaments/detail.html
<h1>{{ tournament.name }}</h1>

{% if tournament.team_set.exists %}
    <ul>
    {% for team in tournament.team_set.all %}
        <li>{{ team.name }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No teams are available.</p>
{% endif %}

tournaments/templates/tournaments/index.html
{% if tournament_list %}
    <ul>
    {% for tournament in tournament_list %}
        <li><a href="{% url 'tournaments:detail' tournament.id %}">{{ tournament.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No tournaments are available.</p>
{% endif %}